funkyBlog/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('create/category', views.create_category_view, name="create_category"),
    path('delete/category/<int:pk>', views.delete_category_view, name="delete_category"),
    path('update/category/<int:pk>', views.update_category_view, name='update_category')
]

funkyBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('funkyBlog.core.urls')),
    path('', include('django.contrib.auth.urls')),
    # path('admin/', admin.site.urls),
]

funkyBlog/core/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.utils.text import slugify


class Category(models.Model):
    """ Forum category model """
    name = models.CharField('Category name', max_length=16, validators=[MinLengthValidator(3)])
    order_number = models.PositiveSmallIntegerField('Order number', default=0)

    class Meta:
        """ Meta class """
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Topic(models.Model):
    """Topic model"""
    name = models.CharField('Topic', max_length=128, validators=[MinLengthValidator(8)])
    created_at = models.DateTimeField('Created date', auto_now_add=True)
    active = models.BooleanField('Active', default=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, blank=False, null=True)

    class Meta:
        """Meta Class"""
        verbose_name_plural = 'Topics'
        verbose_name = 'Topic'

    def __str__(self):
        return slugify(self.name)


class Post(models.Model):
    """ Post Model"""
    text = models.TextField('Text')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, blank=False, null=True)

    class Meta:
        """ Meta class"""
        verbose_name_plural = 'Posts'
        verbose_name = 'Post'

funkyBlog/core/forms.py
""" Forms """

from django.forms import ModelForm
from .models import Category


class CreateCategoryForm(ModelForm):
    """ Create category form """
    class Meta:
        """ Meta class """
        model = Category
        fields = ['name', 'order_number']

funkyBlog/core/views.py
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .forms import  CreateCategoryForm
from .models import Category


class IndexView(ListView):
    """ Index View """
    model = Category
    template_name = "index.html"


index_view = IndexView.as_view()


class CreateCategoryView(CreateView):
    """ Create Category View """
    model = Category
    form_class = CreateCategoryForm
    template_name = "create_category.html"
    success_url = reverse_lazy("core:index")


create_category_view = CreateCategoryView.as_view()


class DeleteCategoryView(DeleteView):
    """ Delete Category View"""
    model = Category
    template_name = "delete_category.html"
    success_url = reverse_lazy('core:index')


delete_category_view = DeleteCategoryView.as_view()


class UpdateCategoryView(UpdateView):
    """ Update category View """
    model = Category
    form_class = CreateCategoryForm
    # fields = ['name']
    template_name = "create_category.html"
    success_url = reverse_lazy('core:index')


update_category_view = UpdateCategoryView.as_view()

funkyBlog/core/templates/base.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% load bootstrap4 static %}

<!-- Overwrite page title -->
{% block bootstrap4_title %}Python Academy Forum{% endblock %}

<!-- Overwrite js extra panel -->
{% block bootstrap4_extra_head %}
    {% bootstrap_javascript jquery='full' %}
{% endblock %}

<!-- Overwrite place before content -->

<!-- Overwrite place before content -->
{% block bootstrap4_before_content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Brand and toggle get grouped for better mobile display -->
    <a class="navbar-brand" href="{% url 'core:index' %}">FunkyBlog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdow-toggle" href="#" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Profile
                    </a>
                    <div class="dropdown-menu" aria-labelledby="profileDropdown">
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                    </div>
                </li>
            {% else %}
                <li class='nav-item {% if "logout" in request.path %} active {% endif %}'>
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div><!-- /.navbar-collapse -->
</nav>
{% endblock %}

{% block bootstrap4_content %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

{% block bootstrap4_after_content %}
<!--  Greate place for footer -->
{% endblock %}

funkyBlog/core/templates/create_category.html
{% extends 'base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
<div class="row">
    <div class="col">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-none d-lg-block d-xl-block">
                {% bootstrap_button "Save" button_type="submit" button_class="btn btn-primary" %}
                <a href="{% url 'core:index' %}" class="btn btn-light">{% trans 'Cancel' %}</a>
            </div>
            <div class="d-lg-none d-xl-none">
                {% bootstrap_button "Save" button_type="submit" button_class="btn btn-primary btn-lg btn-block" %}
                <a href="{% url 'core:index' %}" class="btn btn-light btn-lg btn-block">{% trans 'Cancel' %}</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

funkyBlog/core/templates/delete_category.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
<div class="row">
    <div class="col">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>Are you sure you want delete {{ category.name }} ? </h1>
            <div class="d-none d-lg-block d-xl-block">
                {% bootstrap_button "Delete" button_type="submit" button_class="btn btn-danger" %}
                <a href="{% url 'core:index' %}" class="btn btn-warning">Cancel</a>
            </div>
            <div class="d-lg-none d-xl-none">
                {% bootstrap_button "Delete" button_type="submit" button_class="btn btn-danger btn-lg btn-block" %}
                <a href="{% url 'core:index' %}" class="btn btn-warning btn-lg btn-block">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

funkyBlog/core/templates/index.html
{% extends 'base.html' %}

{% load bootstrap4 static %}

{% block content %}

<div class="row">
    <div class="col">
    <div class="card">
      <div class="card-header">

        <div class="float-left">
            Categories
      </div>
      <div class ="float-right">
          <a href="{% url 'core:create_category' %}" class="badge badge-success">Create new category</a>

      </div>
      </div>
      <ul class="list-group list-group-flush">
        {% if object_list %}
            {% for category in object_list %}
          <li class="list-group-item">{{ category.name }}  <p class="float-right"><a href="{% url 'core:delete_category' category.pk %}" class="badge badge-danger">Delete</a>
              <a href="{% url 'core:update_category' category.pk %}" class="badge badge-primary">Edit</a></p></li>
            {% endfor %}
        {% else %}
          <li class="list-group-item">No categories</li>
        {% endif %}
      </ul>
    </div>
    </div>
</div>
{% endblock %}